"use strict";
console.log('**************************Numbers***************************');
const entero = 10;
console.log('Nro entero:', entero);
const decimal = 10.5;
console.log('Nro decimal:', decimal);
const expo = 2.5e3;
console.log('Nro exponencial:', expo);
const expoNeg = 1.5e-2;
console.log('Nro exponencial negativo:', expoNeg);
const hexa = 0xA;
console.log('Nro hexadecimal:', hexa);
const octal = 0o12;
console.log('Nro octal:', octal);
const bin = 0b1010;
console.log('Nro binario:', bin);
